### PR TITLE
Update BFL and remove apocryph links

### PR DESCRIPTION
**Pull request by spd-intermodalics**
# Description

With this PR, the Source page of BFL points to [Toeklk](https://github.com/toeklk/orocos-bayesian-filtering) (presumibly [Klass Gadeyne](https://www.researchgate.net/profile/Klaas_Gadeyne)) until we clarify how the subproject of BFL is handled.

The PR also updates the [getting started guide](https://orocos.org/bfl/docs/getting_started_guide.pdf) and adds the [installation guide](https://orocos.org/bfl/docs/installation_guide.pdf), which I took from the repository, build them, and uploaded to orocos.org.
I am aware that these guides are outdated w.r.t. the links, but to modify them, we need to patch the most official BFL repository.

### CODE REVIEW

**Review by meyerj — COMMENTED** [review]
Please also update the inconsistent source repo link here:

https://github.com/orocos/orocos-docs/blob/7180dd76e7659c4d3cd9d76a0ee2fb72405b2653/docs/docs_main/sources.rst#L30-L33

The links there should match the "Source" entry of the respective project in the navigation bar, i.e. in [index.rst](https://github.com/orocos/orocos-docs/blob/7180dd76e7659c4d3cd9d76a0ee2fb72405b2653/docs/index.rst).

I think, the PDF files should be directly committed to this repository as binary files, or converted to RST, if one would exist, but not hosted on [orocos.org](https://orocos.org), such that everyone has the chance to update them via a PR in the future and we don't spread documentation over many different servers or even personal web pages again. Automatically generated content (e.g. API documentation) could be hosted on https://orocos.github.io/ (served from https://github.com/orocos/orocos.github.io) like for RTT and OCL, or just reference https://docs.ros.org/api/bfl.

First of all, it would be great to hear from @toeklk and/or @tdelaet whether it is okay to reference https://github.com/toeklk/orocos-bayesian-filtering as the "official" source repository for BFL here, or whether other more recent (or diverged) repositories exist elsewhere?

To my knowledge, there currently is
- https://github.com/toeklk/orocos-bayesian-filtering
- https://gitlab.mech.kuleuven.be/rob-estimation/orocos-bayesian-filtering (redirects to https://gitlab.kuleuven.be/rob-estimation/orocos-bayesian-filtering)
- https://gitlab.kuleuven.be/rob-orocos/bfl
- https://github.com/ros-gbp/bfl-release

The legacy page [orocos.org/bfl](https://www.orocos.org/bfl) only references tar balls at https://orocos.org/orocos/source-code-2.html with broken links, and refers to https://gitlab.mech.kuleuven.be/rob-estimation/orocos-bayesian-filtering on https://orocos.org/bfl/subversion.html.

https://github.com/ros-gbp/bfl-release is definitely not a source repository.

Ideally we could move the "official" one to the https://github.com/orocos organization then, for consistency. At least for GitHub projects like https://github.com/toeklk/orocos-bayesian-filtering, all the previous links to the repos, issues and pull requests will be preserved, with proper redirects ([documentation](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)).

**Comment by meyerj** [comment]
> Ideally we could move the "official" one to the https://github.com/orocos organization then, for consistency. At least for GitHub projects like https://github.com/toeklk/orocos-bayesian-filtering, all the previous links to the repos, issues and pull requests will be preserved, with proper redirects ([documentation](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)).

Done. Could you please update the source links to [https://github.com/orocos/orocos-bayesian-filtering](https://github.com/toeklk/orocos-bayesian-filtering) before merging this PR?

**Review by meyerj — COMMENTED** [review]
I wonder whether there is an easier approach to integrate the generated PDF files. Not only for BFL, but also for other static files added in the future.

`_static` and [html_static_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_static_path) seems to be meant for style-related files and scripts. It might work and likely you tested it, although I cannot imagine that files in `_static` are supposed to be referenced from a reStructuredText document via a relative link like that.

I suggest to try the following alternatives, unless you already did (in priority order):

1. The obvious: Add pdf files to [docs/bfl](https://github.com/orocos/orocos-docs/tree/ee88e1ff90e05644f21be4f651dc3381ac262287/docs/bfl) and link by name without any path, and without modifying `html_static_path` or `html_extra_path`. In the same way as you would reference another rst file.

   The resulting URL would be https://docs.orocos.org/bfl/getting_started_guide.pdf instead of https://docs.orocos.org/_static/bfl_docs/getting_started_guide.pdf, which is nicer for search engines or if the PDF would be linked from somewhere else (e.g. from [orocos_bfl/README.md](https://github.com/orocos/orocos-bayesian-filtering/blob/master/orocos_bfl/README.md)).

2. Add pdf files to `_extra/bfl` instead of `_static/bfl_pdfs`, and set [html_extra_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path) to `['_extra']` instead of [html_static_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_static_path). The references in [overview.rst](https://github.com/orocos/orocos-docs/pull/16/files#diff-24247a41b44f6924d910535f4ac36660) can still be without a path component because the files should end up in the same directory in the output.

   From the [documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path) the difference is not 100% clear to me, but for sure the files added to `html_extra_path = ['_extra']` will be copied directly to the output directory, and not to `_static`.

3. Add pdf files to [docs/bfl](https://github.com/orocos/orocos-docs/tree/ee88e1ff90e05644f21be4f651dc3381ac262287/docs/bfl) as in 1., and link to them using the [`:download:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-download) role. This is what is suggested in the answer of this older [StackOverflow post](https://stackoverflow.com/questions/18621727/how-to-serve-static-non-image-asset-from-a-readthedocs-site), but it may be outdated for current versions of Sphinx. And this approach would force users to download the PDFs instead of reading them in the browser.

I quickly tested 1 and 2 locally, by running `make html` in the `docs/` folder of a working copy of [orocos-docs](https://github.com/orocos/orocos-docs). Both seems to work, but I am not sure whether there are further restrictions if the page is hosted on [readthedocs.io](https://readthedocs.io) for security reasons.

I also enabled pull request builds through ReadTheDocs, so I suggest to update the branch according to 1. and check whether the PR build succeeds and the page is rendered correctly. Agreed?

**Comment by spd-intermodalics** [comment]
I tried the option 1 when created the PR, and double checked now. For me it isn't working. I am not sure how I am doing it differently from your explanation if it worked for you.

The reason for not using the `:download:` tag (option 3) was that I read in some other post that it would provoke to download the file instead of download inline; but I have to admit that didn't try it.

So, at this point, I prefer to use the option 2, which is what I implemented in the last patch.

**Review by meyerj — APPROVED** [review]

**Pull request merged**
